### ISSUE TITLE
Plots shown in IPython notebook are not resizable

### ISSUE THREAD

**Issue by fsaad** [probcomp/bdbcontrib#25] opened 2015-09-14 19:38 UTC
**Figure** (pun intended) out a way to beautify the shape and size of plots returned by the `api` plotting utilities such that IPython notebook renders them nicely.

**Comment by gregory-marton** [comment] 2016-02-18 18:47
Closing as de-facto duplicate of 28.

**Closed by gregory-marton** 2016-02-18 18:47 UTC
