### ISSUE TITLE
recipes uses matplotlib in a way that breaks virtualenv

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bdbcontrib#102] opened 2015-11-12 05:07 UTC
Matplotlib doesn't like virtualenv for native backends. http://matplotlib.org/1.5.0/faq/virtualenv_faq.html

recipes appears to be importing it in a way that always gets a native backend instead of sometimes getting the notebook backend.

Error message:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-53b766d88722> in <module>()
      3 import bdbcontrib
      4 from bdbcontrib import cursor_to_df as df
----> 5 from bdbcontrib.recipes import quickstart
      6 
      7 import matplotlib.pyplot as plt

/Users/tibbetts/bayesdb/lib/python2.7/site-packages/bdbcontrib/recipes.py in <module>()
     23 import crosscat
     24 import crosscat.LocalEngine
---> 25 import matplotlib.pyplot as plt
     26 import re
     27 import os

/Users/tibbetts/bayesdb/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    112 
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115 
    116 _IP_REGISTERED = None

/Users/tibbetts/bayesdb/lib/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/Users/tibbetts/bayesdb/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py in <module>()
     22 
     23 import matplotlib
---> 24 from matplotlib.backends import _macosx
     25 
     26 

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

**Comment by tibbetts** [comment] 2015-11-12 05:18
A work around is to install ipython globally and not in your virtualenv and then invoke the global ipython while the virtualenv is activated.

**Comment by gregory-marton** [comment] 2015-11-23 14:08
I'm most curious about the "sometimes" part. Is this something you can regularly reproduce? I saw this on the test machine some time ago, reproducably (though not with recipes) and thought that I had fixed it by setting the appropriate matplotlib environment variable to backend being pdf on osx before starting the notebook, but perhaps it works differently when you're using the recipes notebook (the one in bdbcontrib at head) instead of the default bayesdb-demo notebook?

**Comment by raxraxraxraxrax** [comment] 2015-12-22 20:29
I had this problem when I tried to build from source, but it worked fine in an 0.1.4 alpha .dmg. I was not able to use the workaround I was able to find. From my lab notebook: 

"I discovered http://matplotlib.org/1.5.0/faq/virtualenv_faq.html which has some workarounds at the bottom. I put the python script into my virtualenv and started bayesdb-demo as follows: 
rax$ frameworkpython ~/build-bayesdb/bayesdb-0.1.3-head/bin/bayesdb-demo

Unfortunately that got me the same error as before: http://pastebin.com/B0Z5G6j0

There’s also a github package on that page, so I’m going to try that next. And that doesn’t work either."

This context is no longer in my head. If it would help to look at this on my laptop, I have not deleted this virtualenv.

**Comment by gregory-marton** [comment] 2015-12-30 02:26
Given that @raxraxraxraxrax confirmed this working with an 0.1.4 dmg, and that our osx-tests are regularly succeeding (which build from source), and that I can't reproduce it on my laptop, I'm going to close this. If anyone still finds a problem, please reopen with more info.

**Closed by gregory-marton** 2015-12-30 02:26 UTC
Labels: 014 high
